name: torch_tqdm_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311hee9e2a2_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h8818502_7
  - aws-c-cal=0.9.10=hca30140_1
  - aws-c-common=0.12.5=hc919400_1
  - aws-c-compression=0.3.1=h61d5560_8
  - aws-c-event-stream=0.5.6=h18584fc_6
  - aws-c-http=0.10.7=hcd69b29_4
  - aws-c-io=0.23.3=h9710c81_3
  - aws-c-mqtt=0.13.3=ha255ef3_10
  - aws-c-s3=0.10.1=hd860258_2
  - aws-c-sdkutils=0.2.4=h61d5560_3
  - aws-checksums=0.2.7=h61d5560_4
  - aws-crt-cpp=0.35.2=h5596a46_4
  - aws-sdk-cpp=1.11.606=h95becb6_7
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - blas=2.301=openblas
  - blas-devel=3.11.0=1_h11c0a38_openblas
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py311h69b7e7c_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311hcfc1310_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h5a5e7c7_3
  - cpython=3.11.14=py311hd8ed1ab_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - datasets=4.4.1=pyhcf101f3_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - dill=0.4.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_h670d5b4_106
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - frozenlist=1.7.0=py311h8740443_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.1=heb240a5_0
  - glslang=16.0.0=h60b4770_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py311hd340a2e_2
  - graphite2=1.3.14=hec049ff_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=haf38c7b_0
  - hf-xet=1.2.0=py310h6ce4931_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - kaldi=5.5.1172=cpu_h0f61937_2
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=22.0.0=h4a3aeba_4_cpu
  - libarrow-acero=22.0.0=hc317990_4_cpu
  - libarrow-compute=22.0.0=h75845d1_4_cpu
  - libarrow-dataset=22.0.0=hc317990_4_cpu
  - libarrow-substrait=22.0.0=h144af7f_4_cpu
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.11.0=1_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.11.0=1_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.6=hf598326_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.0=h1bb475b_0
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=1_hd9741b5_openblas
  - liblapacke=3.11.0=1_h1b118fd_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libparquet=22.0.0=h0ac143b_4_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - librsvg=2.60.0=h5c55ec3_0
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libtorch=2.8.0=cpu_generic_h0fc8bc6_2
  - libusb=1.0.29=hbc156a2_0
  - libutf8proc=2.11.1=hd2415e0_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.5=h4a912ad_2
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py311h30e7462_0
  - multiprocess=0.70.18=py311h5bb9006_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h248ca61_1
  - nomkl=3.0=0
  - numpy=2.3.5=py311h8685306_0
  - openblas=0.3.30=openmp_hea878ba_3
  - openfst=1.8.4=ha393de7_1
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - optree=0.18.0=py311h5a5e7c7_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_1
  - pango=1.56.4=h875632e_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h7125dd6_0
  - pillow=12.0.0=py311h890502c_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - prometheus-cpp=1.3.0=h0967b3e_0
  - propcache=0.3.1=py311h4921393_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.15=hd3d436d_0
  - pyarrow=22.0.0=py311ha1ab1f8_0
  - pyarrow-core=22.0.0=py311hf3e52b4_0_cpu
  - pybind11=2.13.6=py311h2c37856_0
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=py311h2c37856_0
  - pycparser=2.22=pyh29332c3_1
  - pyfastx=2.2.0=py311h84f6924_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.12=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.11.14=hd8ed1ab_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py311hacbd903_1
  - python_abi=3.11=8_cp311
  - pytorch=2.8.0=cpu_generic_py311_hf0c13c8_2
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - regex=2025.11.3=py311h9408147_1
  - requests=2.32.5=pyhd8ed1ab_0
  - safetensors=0.6.2=py311h0f0954d_2
  - scipy=1.16.3=py311h2734c94_1
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.26=h919df07_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h1a5098f_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - spirv-tools=2025.4=ha7d2532_0
  - statsmodels=0.14.5=py311h09efe57_1
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h66ce52b_1
  - tk=8.6.13=h892fb3f_3
  - tokenizers=0.22.1=py311h4175fc0_1
  - torchaudio=2.8.0=cpu_py311h25c3968_2
  - torchcodec=0.8.1=cpu_py311_h5cec8ce_2
  - torchvision=0.24.0=cpu_py311_hbf31bb3_2
  - torchvision-extra-decoders=0.0.2=py311h231fa4a_4
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.57.1=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py311h9408147_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xxhash=0.8.3=haa4e116_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py311ha9b3269_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py311h5bb9006_1
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/anaconda3/envs/torch_tqdm_env
