name: BioMechInterp
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiodns=3.5.0=py311hca03da5_0
  - aiohappyeyeballs=2.6.1=py311hca03da5_0
  - aiohttp=3.12.15=py311h79febb2_0
  - aiosignal=1.4.0=py311hca03da5_0
  - attrs=25.4.0=py311hca03da5_0
  - aws-c-auth=0.9.0=h80987f9_1
  - aws-c-cal=0.9.2=h80987f9_0
  - aws-c-common=0.12.3=h80987f9_0
  - aws-c-compression=0.3.1=h80987f9_1
  - aws-c-event-stream=0.5.5=h80987f9_0
  - aws-c-http=0.10.2=h80987f9_0
  - aws-c-io=0.20.1=h80987f9_0
  - aws-c-mqtt=0.13.2=h8532080_0
  - aws-c-s3=0.8.3=h80987f9_0
  - aws-c-sdkutils=0.2.4=h80987f9_0
  - aws-checksums=0.2.7=h80987f9_0
  - aws-crt-cpp=0.32.10=h313beb8_0
  - aws-sdk-cpp=1.11.510=h3a747ed_13
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - blas=1.0=openblas
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.9.9=hca03da5_0
  - certifi=2025.10.5=py311hca03da5_0
  - cffi=2.0.0=py311h3a083c1_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - datasets=2.14.4=pyhd8ed1ab_0
  - dill=0.3.7=py311hca03da5_0
  - filelock=3.17.0=py311hca03da5_0
  - freetype=2.13.3=hce30654_1
  - frozenlist=1.8.0=py311h50f4ffc_0
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gflags=2.2.2=h313beb8_1
  - giflib=5.2.2=h80987f9_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - hf-xet=1.1.8=py311h8cd5084_0
  - huggingface_hub=0.34.4=py311hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py311hca03da5_0
  - importlib-metadata=8.5.0=py311hca03da5_0
  - jinja2=3.1.6=py311hca03da5_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=he4db4b2_2
  - lcms2=2.15=h481adae_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.1=cxx17_h07bc746_0
  - libarrow=20.0.0=hd5f8272_8_cpu
  - libarrow-acero=20.0.0=hf07054f_8_cpu
  - libarrow-dataset=20.0.0=hf07054f_8_cpu
  - libarrow-substrait=20.0.0=he749cb8_8_cpu
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=11_h742a510_netlib
  - libcrc32c=1.1.2=hc377ac9_0
  - libcurl=8.15.0=hcdd2897_0
  - libcxx=20.1.3=ha82da77_0
  - libdeflate=1.17=h1a8c8d9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - libgoogle-cloud=2.36.0=h9484b08_1
  - libgoogle-cloud-storage=2.36.0=h7081f7f_1
  - libgrpc=1.71.0=h857da87_1
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=2.1.4=h1a8c8d9_0
  - liblapack=3.9.0=11_hd5e45d6_netlib
  - liblzma=5.8.1=h39f12f2_0
  - liblzma-devel=5.8.1=h39f12f2_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libopentelemetry-cpp=1.21.0=h0181452_0
  - libopentelemetry-cpp-headers=1.21.0=hce30654_0
  - libparquet=20.0.0=h636d7b7_8_cpu
  - libpng=1.6.47=h3783ad8_0
  - libprotobuf=5.29.3=hccd9074_1
  - libre2-11=2025.06.26=hd41c47c_0
  - libsqlite=3.49.1=h3f77e49_2
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.21.0=h64651cc_0
  - libtiff=4.5.0=h5dffbdd_2
  - libtorch=2.5.1=cpu_generic_h9a9d006_17
  - libutf8proc=2.10.0=h74a6958_0
  - libuv=1.50.0=h5505292_0
  - libwebp=1.2.4=h999c80f_1
  - libwebp-base=1.2.4=h1a8c8d9_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.3=hdb05f8b_0
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.2=py311h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - multidict=6.7.0=py311h254cc4a_0
  - multiprocess=0.70.15=py311hca03da5_0
  - ncurses=6.5=h5e97a16_3
  - networkx=3.4.2=py311hca03da5_0
  - nlohmann_json=3.11.2=h313beb8_0
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.0.1=py311he598dae_1
  - numpy-base=2.0.1=py311hfbfe69c_1
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.5.0=h81ee809_0
  - orc=2.1.2=hd90e43c_0
  - packaging=25.0=py311hca03da5_1
  - pandas=2.2.3=py311hca32420_3
  - pillow=9.4.0=py311h627eb56_1
  - pip=25.0.1=pyh8b19718_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - propcache=0.3.1=py311h80987f9_0
  - pthread-stubs=0.3=h1a28f6b_1
  - pyarrow=20.0.0=py311ha1ab1f8_0
  - pyarrow-core=20.0.0=py311he04fa90_0_cpu
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - pycares=4.10.0=py311h091efcb_0
  - pycparser=2.23=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.12=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py311h80987f9_0
  - python_abi=3.11=7_cp311
  - pytorch=2.5.1=cpu_generic_py311_hc7d8f6d_17
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h80987f9_0
  - re2=2025.06.26=h6589ca4_0
  - readline=8.2=h1d1bf99_2
  - regex=2025.9.1=py311h254cc4a_0
  - requests=2.32.3=py311hca03da5_1
  - safetensors=0.5.3=py311hc2e03bc_0
  - scikit-learn=1.6.1=py311h47fa2fb_0
  - scipy=1.15.2=py311h0675101_0
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h8391f65_0
  - snappy=1.2.1=h313beb8_0
  - sympy=1.13.3=py311hca03da5_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h5083fa2_1
  - tokenizers=0.19.1=py311he19d34d_0
  - torchaudio=2.5.1=py311_cpu
  - torchvision=0.20.1=py311_cpu
  - tqdm=4.67.1=py311hb6e6a13_0
  - transformers=4.44.1=py311hca03da5_0
  - typing-extensions=4.12.2=py311hca03da5_0
  - typing_extensions=4.12.2=py311hca03da5_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.3.0=py311hca03da5_0
  - uvloop=0.21.0=py311h80987f9_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.8.1=h9a6d368_0
  - xz-gpl-tools=5.8.1=h9a6d368_0
  - xz-tools=5.8.1=h39f12f2_0
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.18.0=py311h80987f9_0
  - zipp=3.21.0=py311hca03da5_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - einops==0.8.1
      - inquirerpy==0.3.4
      - pfzy==0.3.4
      - prompt-toolkit==3.0.52
      - pyfastx==2.2.0
      - wcwidth==0.2.14
prefix: /opt/anaconda3/envs/BioMechInterp
